---
abstract: 'Find a minimum required version of perl for Perl code'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  File::Spec::Functions: '0'
  Test::More: '0.47'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.017, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Perl-MinimumVersion
no_index:
  directory:
    - eg
    - examples
    - inc
    - share
    - t
    - xt
provides:
  Perl::MinimumVersion:
    file: lib/Perl/MinimumVersion.pm
    version: '1.40'
  Perl::MinimumVersion::Reason:
    file: lib/Perl/MinimumVersion/Reason.pm
    version: '1.40'
requires:
  Carp: '0'
  Exporter: '0'
  File::Find::Rule: '0'
  File::Find::Rule::Perl: '0'
  File::Spec: '0'
  Getopt::Long: '0'
  List::Util: '1.20'
  PPI: '1.215'
  PPI::Util: '0'
  PPIx::Regexp: '0.033'
  PPIx::Utils: '0'
  Params::Util: '0.25'
  perl: '5.006'
  strict: '0'
  vars: '0'
  version: '0.76'
  warnings: '0'
resources:
  homepage: https://github.com/neilb/Perl-MinimumVersion
  repository: https://github.com/neilb/Perl-MinimumVersion.git
version: '1.40'
x_contributors:
  - 'Adam Kennedy <adam@ali.as>'
  - 'Alexandr Ciornii <alexchorny@gmail.com>'
  - 'Chris Dolan <chris+github@chrisdolan.net>'
  - 'Dan Book <grinnz@gmail.com>'
  - 'Dan Book <grinnz@grinnz.com>'
  - 'Elliot Shank <elliotjs@cpan.org>'
  - 'Jakub Wilk <jwilk@jwilk.net>'
  - 'Leon Timmermans <fawaka@gmail.com>'
  - 'Neil Bowers <neil@bowers.com>'
  - 'Ricardo Signes <rjbs@cpan.org>'
  - 'Steffen Müller <smueller@cpan.org>'
  - 'Yanick Champoux <yanick@babyl.dyndns.org>'
x_generated_by_perl: v5.32.1
x_serialization_backend: 'YAML::Tiny version 1.73'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
